### ISSUE TITLE
Ensure `task_funds_withdrawn` table gets populated

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/indexer-sweep#2]
I didn't see `task_funds_withdrawn` in the project, which means there aren't rows getting added there.

**Comment by mikedotexe** [comment]
Depends on https://github.com/CronCats/cw-croncat/issues/190

**Comment by nlipartiia-hacken** [comment]
I think it should be closed since we decided to remove `task_funds_withdrawn`.

**Comment by mikedotexe** [comment]
> I think it should be closed since we decided to remove `task_funds_withdrawn`.

good point, thank you!
